---
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/inventory-mgmt
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 7070     
synerzip:
  user:
    bu: BU-9